export const enum AgeRangeTypeProto {
  UNDER_TEEN = "UNDER_TEEN",
  TEENS = "TEENS",
  TWENTIES = "TWENTIES",
  THIRTIES = "THIRTIES",
  FORTIES = "FORTIES",
  FIFTIES = "FIFTIES",
  OVER_FIFTY = "OVER_FIFTY",
}